server:
  servlet:
    context-path: /niel

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/niel_web_shop?serverTimezone=UTC&characterEncoding=utf8
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    generate-ddl: false
  mvc:
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
    enabled: true
    drop-first: false